### ISSUE TITLE
Package missing in maven jar

### ISSUE THREAD

**Issue by josangel555** [digitalpetri/opc-ua-sdk-examples#1]
I am trying to recreate the `opc-ua-sdk-examples`. I am getting an error in `ClientExampleRunner.java`.

In the part where we create a new `config` object of type `OpcUaClientConfig`, I am getting the following error.

`The type com.digitalpetri.opcua.stack.client.config.UaTcpStackClientConfigBuilder cannot be resolved. It is indirectly referenced from required .class files`

While checking the Maven Dependencies folder, I could see that the package named `com.digitalpetri.opcua.stack.client.config` is missing in the jar file, `stack-client-1.0.0-SNAPSHOT.jar`.

I could see the package and java file in the `opc-ua-stack` git repo. I guess the jar given by maven is not updated. Could you please look into this issue. (I tried to build the module (`opc-ua-stack`) from repo but i'm getting some errors :( ) .

Below are my maven imports,

```
     <dependency>
            <groupId>com.digitalpetri.opcua</groupId>
            <artifactId>ua-client</artifactId>
            <version>1.0.0-SNAPSHOT</version>
    </dependency>

    <dependency>
        <groupId>com.digitalpetri.opcua</groupId>
        <artifactId>ua-server</artifactId>
        <version>0.4.0-SNAPSHOT</version>
    </dependency>

    <dependency>
            <groupId>com.digitalpetri.opcua</groupId>
            <artifactId>ctt-namespace</artifactId>
            <version>0.4.0-SNAPSHOT</version>
    </dependency>
```

This is the package structure in `stack-client-1.0.0-SNAPSHOT.jar`

```
    - com.digitalpetri.opcua.stack.client
      - fsm
        - states
        - ConnectionStateContext.class
        - ConnectionStateEvent.class
      - handlers
        - ...
      - UaTcpStackClient.class
      - UaTcpStackClientConfig.class
```

**Comment by kevinherron** [comment]
Okay, I did this in a VM after deleting ~/.m2/repository so that nothing was cached and I could not reproduce what you're seeing.

Since you have the projects cloned, it might help to do this:
1a) make sure you have the latest revision of opc-ua-stack
1b) do a `mvn install` for opc-ua-stack
2) if you have the previous combined opc-ua-sdk project, remove that
3a) clone and/or update [ua-server-sdk](https://github.com/digitalpetri/ua-server-sdk)
3b) do a `mvn install` for [ua-server-sdk](https://github.com/digitalpetri/ua-server-sdk)
4a) clone and/or update [ua-client-sdk](https://github.com/digitalpetri/ua-client-sdk)
4b) do a `mvn install` for [ua-client-sdk](https://github.com/digitalpetri/ua-client-sdk)

Also make sure you're building with Java 8. If this still doesn't work, you might trying blowing away your maven repo cache (everything under `~/.m2/repository/com/digitalpetri` would be enough).

**Comment by josangel555** [comment]
Thanks Kevin for the help. I cleared the folder in maven repo and it solved the issue. Also I was able to build the modules using the steps you mentioned.
